// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOWYnrPoDXqSgqSpDnN4JjhEC3kV4faA8',
    appId: '1:362390417969:web:3bfffdbbb9ecbed458db10',
    messagingSenderId: '362390417969',
    projectId: 'authentication-812a0',
    authDomain: 'authentication-812a0.firebaseapp.com',
    storageBucket: 'authentication-812a0.appspot.com',
    measurementId: 'G-NW467PQZ1F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2N6U6edhYR92oS9tfG75SnRGvO8OUQC0',
    appId: '1:362390417969:android:9d150959815c079958db10',
    messagingSenderId: '362390417969',
    projectId: 'authentication-812a0',
    storageBucket: 'authentication-812a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9_iWXLKOwbPlUNNX5pae7k0hNsJBlj7s',
    appId: '1:362390417969:ios:5823967fb31783b658db10',
    messagingSenderId: '362390417969',
    projectId: 'authentication-812a0',
    storageBucket: 'authentication-812a0.appspot.com',
    androidClientId: '362390417969-sqs2mv5ctkg4ttv8gufnol05d3fuevm9.apps.googleusercontent.com',
    iosClientId: '362390417969-lgv5cim6qur9eg4odj3hf6ani9lg0q8t.apps.googleusercontent.com',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9_iWXLKOwbPlUNNX5pae7k0hNsJBlj7s',
    appId: '1:362390417969:ios:5823967fb31783b658db10',
    messagingSenderId: '362390417969',
    projectId: 'authentication-812a0',
    storageBucket: 'authentication-812a0.appspot.com',
    androidClientId: '362390417969-sqs2mv5ctkg4ttv8gufnol05d3fuevm9.apps.googleusercontent.com',
    iosClientId: '362390417969-lgv5cim6qur9eg4odj3hf6ani9lg0q8t.apps.googleusercontent.com',
    iosBundleId: 'com.example.authentication',
  );
}
